name: GeoPython37env
channels:
  - conda-forge
  - numba
  - rapidsai
  - mro
  - r
  - defaults
dependencies:
  - python==3.7
  - asciitree
  - autopep8
  - babel
  - basemap
  - beautifulsoup4
  - blas
  - blaze
  - bokeh
  - bzip2
  - cartopy
  - colorcet
  - curl
  - cython
  - cytoolz
  - dask
  - dask-core
  - datashader
  - datashape
  - descartes
  - dill
  - docutils
  - earthengine-api
  - fiona
  - gcc
  - gensim
  - geographiclib
  - geopandas
  - geoplot
  - geopy
  - geotiff
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - georasters
  - imageio
  - imagesize
  - ipykernel
  - ipyparallel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - jupyterlab
  - kiwisolver
  - matplotlib
  - markdown
  - networkx
  - nose
  - numba
  - numpy
  - openpyxl
  - pandas
  - pandas-datareader
  - pandasql
  - pandoc
  - pandocfilters
  - pandana
  - pelican
  - pycountry
  - pymc3
  - pysal
  - python.app
  - urbanaccess
  - r
  - rstudio
  - r-irkernel
  - statsmodels
  - sympy
  - rpy2
  - rasterio
  - r-tidyr
  - r-tibble
  - r-dplyr
  - rise
  - seaborn
  - scikit-allel
  - scikit-bio
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - swifter
  - theano
  - unidecode
  - urllib3
  - wikipedia
  - xlrd
  - jupyter_contrib_nbextensions
  - pip:
    - linearmodels
    - isounidecode
    - geonamescache
    - geocoder
    - git+https://github.com/jeetsukumaran/DendroPy.git
    - git+https://github.com/dmsul/econtools
    - ecopy
    - facebook- business
    - facebook- sdk
    - fontawesome- markdown
    - geocoder
    - geonamescache
    - googledrivedownloader
    - googletrans
    - ipystata
    - isodate
    - isounidecode
    - latexcodec
    - ldpred
    - linearmodels
    - lingpy
    - mccabe
    - ordered- set
    - plinkio
    - pyarrow
    - pybtex
    - pycldf
    - pycountry
    - pydocstyle
    - pyface
    - pyflakes
    - pylatex
    - pyparsing
    - pyreadstat
    - pytest- cov
    - python- jsonrpc- server
    - python- language- server
    - pytrends
    - quilt
    - ratelim
    - readme- renderer
    - rfc3986
    - rope
    - simpledbf
    - simplejson
    - smartypants
    - snowballstemmer
    - snuggs
    - stata- kernel
    - tabulate
    - tex2ipy
    - texsoup
    - toolz
    - traits
    - traitsui
    - twine
    - typogrify
    - uritemplate
    - w3lib
    - webencodings
    - wrapt
    - xlwt
    - yapf
    - modin
    - stargazer
    - covid
    - COVID19Py
