name: GeoPython37env
channels:
  - conda-forge
  - numba
  - rapidsai
  - mro
  - r
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - affine=2.3.0
  - asciitree=0.3.3
  - attrs=19.3.0
  - autopep8=1.4.4
  - babel=2.7.0
  - backcall=0.1.0
  - basemap=1.2.1
  - bcolz=1.2.1
  - beautifulsoup4=4.8.1
  - blas=2.12
  - blaze=0.11.3
  - bleach=3.1.0
  - blinker=1.4
  - blosc=1.17.0
  - bokeh=1.4.0
  - boost-cpp=1.70.0
  - boto=2.49.0
  - boto3=1.12.1
  - botocore=1.15.1
  - bwidget=1.9.14
  - bz2file=0.98
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cachecontrol=0.12.5
  - cachetools=3.1.1
  - cairo=1.16.0
  - cartopy=0.17.0
  - cctools=895
  - certifi=2020.4.5.1
  - cffi=1.13.2
  - cfitsio=3.470
  - chardet=3.0.4
  - clang=4.0.1
  - clang_osx-64=4.0.1
  - clangxx=4.0.1
  - clangxx_osx-64=4.0.1
  - click-plugins=1.1.1
  - cloog=0.18.0
  - cloudpickle=1.3.0
  - colorcet=2.0.1
  - compiler-rt=4.0.1
  - contextily=1.0rc2
  - cryptography=2.8
  - curl=7.65.3
  - cycler=0.10.0
  - cyrus-sasl=2.1.27
  - cython=0.29.13
  - cytoolz=0.10.1
  - dask=2.8.0
  - dask-core=2.8.0
  - datashader=0.8.0
  - datashape=0.5.4
  - dbus=1.13.6
  - decorator=4.4.1
  - defusedxml=0.6.0
  - deprecated=1.2.7
  - descartes=1.1.0
  - dill=0.3.1.1
  - distributed=2.8.0
  - docutils=0.15.2
  - earthengine-api=0.1.206
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.5
  - fasteners=0.14.1
  - feedgenerator=1.9.1
  - fiona=1.8.6
  - flask=1.1.1
  - flask-cors=3.0.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-anaconda=1
  - freetype=2.10.0
  - freexl=1.0.5
  - fribidi=1.0.5
  - fsspec=0.6.2
  - future=0.18.2
  - gdal=2.4.1
  - gensim=3.8.0
  - geographiclib=1.50
  - geopandas=0.6.2
  - geoplot=0.4.0
  - geopy=1.20.0
  - geos=3.7.2
  - geotiff=1.4.3
  - gettext=0.19.8.1
  - gfortran_osx-64=4.8.5
  - giflib=5.1.7
  - glib=2.58.3
  - gmp=5.1.2
  - google-api-core=1.16.0
  - google-api-python-client=1.7.11
  - google-auth=1.7.0
  - google-auth-httplib2=0.0.3
  - google-cloud-core=1.3.0
  - google-cloud-storage=1.23.0
  - google-resumable-media=0.5.0
  - googleapis-common-protos=1.51.0
  - graphite2=1.3.13
  - gsl=2.5
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - hdmedians=0.13
  - heapdict=1.0.1
  - httplib2=0.17.0
  - icu=64.2
  - idna=2.8
  - imageio=2.6.1
  - imagesize=1.1.0
  - importlib_metadata=1.5.0
  - ipykernel=5.1.3
  - ipyparallel=6.2.4
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isl=0.12.2
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jmespath=0.9.4
  - joblib=0.14.1
  - jpeg=9c
  - json-c=0.13.1
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.6.2
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab=1.2.3
  - jupyterlab_server=1.0.6
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - ld64=274.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=2.4.1
  - libgpuarray=0.7.6
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnetcdf=4.6.2
  - libntlm=1.4
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=11.5
  - libprotobuf=3.9.2
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm=4.0.1
  - llvm-lto-tapi=4.0.1
  - llvm-openmp=9.0.1
  - llvmlite=0.29.0
  - locket=0.2.0
  - lockfile=0.12.2
  - lxml=4.5.0
  - lz4-c=1.8.3
  - make=4.2.1
  - mako=1.1.0
  - mapclassify=2.2.0
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=2.2.4
  - matplotlib-base=2.2.4
  - mercantile=1.1.2
  - mistune=0.8.4
  - mock=3.0.5
  - monotonic=1.5
  - more-itertools=8.2.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - msgpack-python=0.6.2
  - multipledispatch=0.6.0
  - munch=2.5.0
  - natsort=7.0.1
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - networkx=2.4
  - nose=1.3.7
  - notebook=6.0.3
  - numba=0.45.1
  - numcodecs=0.6.3
  - numexpr=2.7.0
  - numpy=1.17.3
  - odo=0.5.1
  - olefile=0.46
  - openjdk=8.0.192
  - openjpeg=2.3.1
  - openpyxl=3.0.1
  - openssl=1.1.1g
  - osmnet=0.1.5
  - owslib=0.19.1
  - packaging=20.1
  - palettable=3.3.0
  - pandana=0.4.4
  - pandas-datareader=0.8.1
  - pandasql=0.7.3
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - pango=1.42.4
  - param=1.9.3
  - parso=0.6.1
  - partd=1.1.0
  - patsy=0.5.1
  - pcre=8.41
  - pelican=4.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=20.0.2
  - pixman=0.38.0
  - pluggy=0.13.0
  - pomegranate=0.11.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.5
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - protobuf=3.9.2
  - psutil=5.6.7
  - ptyprocess=0.6.0
  - py=1.8.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.5.0
  - pycountry=19.8.18
  - pycparser=2.19
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pyepsg=0.4.0
  - pygments=2.5.2
  - pygpu=0.7.6
  - pykdtree=1.3.1
  - pymc3=3.7
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pysal=2.1.0
  - pyshp=2.1.0
  - pysocks=1.7.1
  - pytables=3.5.2
  - pytest=5.3.5
  - python=3.7.3
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyyaml=5.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - r=3.6
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bit=1.1_15.2
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.2.1
  - r-boot=1.3_24
  - r-callr=3.4.3
  - r-catools=1.17.1.2
  - r-cellranger=1.1.0
  - r-class=7.3_15
  - r-cli=2.0.1
  - r-clipr=0.7.0
  - r-cluster=2.1.0
  - r-codetools=0.2_16
  - r-collections=0.2.4
  - r-config=0.3
  - r-crayon=1.3.4
  - r-curl=4.3
  - r-cyclocomp=1.1.0
  - r-dbi=1.1.0
  - r-dbplyr=1.4.2
  - r-desc=1.2.0
  - r-digest=0.6.21
  - r-dplyr=0.8.3
  - r-ellipsis=0.3.0
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-forcats=0.4.0
  - r-foreign=0.8_75
  - r-forge=0.2.0
  - r-fs=1.3.1
  - r-generics=0.0.2
  - r-glue=1.3.1
  - r-haven=2.1.1
  - r-highr=0.8
  - r-hms=0.5.3
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.5.1
  - r-httpuv=1.5.2
  - r-httr=1.4.1
  - r-irdisplay=0.7
  - r-irkernel=1.0.2
  - r-jsonlite=1.6.1
  - r-kernsmooth=2.23_15
  - r-knitr=1.28
  - r-languageserver=0.3.5
  - r-later=0.8.0
  - r-lattice=0.20_38
  - r-lazyeval=0.2.2
  - r-lifecycle=0.1.0
  - r-lintr=2.0.1
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_51.5
  - r-matrix=1.2_18
  - r-mgcv=1.8_31
  - r-mime=0.9
  - r-miniui=0.1.1.1
  - r-mongolite=2.1.0
  - r-nlme=3.1_141
  - r-nnet=7.3_12
  - r-odbc=1.1.6
  - r-openssl=1.4.1
  - r-packrat=0.5.0
  - r-pbdzmq=0.3_3
  - r-pillar=1.4.3
  - r-pkgconfig=2.0.3
  - r-pki=0.1_5.1
  - r-plogr=0.2.0
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.2
  - r-profvis=0.3.6
  - r-progress=1.2.2
  - r-promises=1.0.1
  - r-ps=1.3.2
  - r-purrr=0.3.3
  - r-r.cache=0.14.0
  - r-r.methodss3=1.8.0
  - r-r.oo=1.23.0
  - r-r.utils=2.9.2
  - r-r2d3=0.2.3
  - r-r6=2.4.1
  - r-rappdirs=0.3.1
  - r-rcpp=1.0.2
  - r-rcurl=1.98_1.1
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-recommended=3.6
  - r-rematch=1.0.1
  - r-rematch2=2.1.1
  - r-remotes=2.1.1
  - r-repr=1.1.0
  - r-rex=1.1.2
  - r-rjava=0.9_11
  - r-rjdbc=0.2_7.1
  - r-rjsonio=1.3_1.2
  - r-rlang=0.4.4
  - r-rmarkdown=2.1
  - r-rpart=4.1_15
  - r-rprojroot=1.3_2
  - r-rsconnect=0.8.16
  - r-rstudioapi=0.11
  - r-shiny=1.3.2
  - r-sourcetools=0.1.7
  - r-sparklyr=1.1.0
  - r-spatial=7.3_11
  - r-stringdist=0.9.5.5
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-styler=1.3.2
  - r-survival=3.1_8
  - r-sys=3.3
  - r-testthat=2.2.1
  - r-tibble=2.1.3
  - r-tidyr=1.0.0
  - r-tidyselect=1.0.0
  - r-tinytex=0.19
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-vctrs=0.2.2
  - r-withr=2.1.2
  - r-xfun=0.12
  - r-xml2=1.2.2
  - r-xmlparsedata=1.0.3
  - r-xptr=1.1.2
  - r-xtable=1.8_4
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - rasterio=1.0.25
  - readline=8.0
  - requests=2.22.0
  - rise=5.6.0
  - rpy2=3.1.0
  - rsa=4.0
  - rstudio=1.1.456
  - rtree=0.9.4
  - s3transfer=0.3.3
  - scikit-allel=1.2.1
  - scikit-bio=0.5.5
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=45.2.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - simplejson=3.17.0
  - sip=4.19.8
  - six=1.14.0
  - smart_open=1.9.0
  - snuggs=1.4.7
  - sortedcontainers=2.1.0
  - soupsieve=1.9.4
  - sqlalchemy=1.3.13
  - sqlite=3.30.1
  - statsmodels=0.10.1
  - swifter=0.294
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - theano=1.0.4
  - tk=8.6.10
  - tktable=2.10
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.42.1
  - traitlets=4.3.3
  - tzcode=2019a
  - tzlocal=2.0.0
  - unidecode=1.1.1
  - unixodbc=2.3.7
  - urbanaccess=0.2.0
  - uritemplate=3.0.1
  - urllib3=1.25.7
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=1.0.0
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wikipedia=1.4.0
  - wrapt=1.12.0
  - xarray=0.15.0
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xz=5.2.4
  - yaml=0.2.2
  - zarr=2.3.2
  - zeromq=4.3.2
  - zict=1.0.0
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.4.0
  - pip:
    - appdirs==1.4.3
    - click==7.0
    - cligj==0.5.0
    - clldutils==3.4.0
    - colorlog==4.0.2
    - coverage==5.0b1
    - coveralls==1.1
    - covid==2.1.0
    - covid19py==0.3.0
    - csvw==1.6.0
    - curlify==2.2.1
    - dendropy==4.4.0
    - econtools==0.3.0
    - ecopy==0.1.2.2
    - facebook-business==5.0.2
    - facebook-sdk==3.1.0
    - fontawesome-markdown==0.2.6
    - geocoder==1.38.1
    - geonamescache==1.1.0
    - googledrivedownloader==0.4
    - googletrans==2.4.0
    - ipystata==0.3.8
    - isodate==0.6.0
    - isounidecode==0.3
    - jupyter==1.0.0
    - keyring==19.2.0
    - latexcodec==1.0.7
    - ldpred==1.0.10
    - linearmodels==4.14
    - lingpy==2.6.5
    - mccabe==0.6.1
    - modin==0.6.3
    - mypy-extensions==0.4.3
    - ordered-set==3.1.1
    - pandas==0.25.3
    - pkginfo==1.5.0.1
    - plinkio==0.9.7
    - property-cached==1.6.3
    - pyarrow==0.15.1
    - pybtex==0.22.2
    - pycldf==1.8.2
    - pydantic==1.4
    - pydocstyle==4.0.1
    - pyface==6.1.2
    - pyflakes==2.1.1
    - pylatex==1.3.1
    - pyreadstat==0.2.9
    - pytest-cov==2.8.1
    - python-jsonrpc-server==0.3.0
    - python-language-server==0.31.1
    - pytrends==4.7.2
    - quilt==2.9.15
    - rasterstats==0.13.1
    - ratelim==0.1.6
    - readme-renderer==24.0
    - requests-toolbelt==0.9.1
    - rfc3986==1.3.2
    - rope==0.14.0
    - simpledbf==0.2.6
    - smartypants==2.0.1
    - snowballstemmer==2.0.0
    - stargazer==0.0.3
    - stata-kernel==1.10.5
    - tabulate==0.8.6
    - tex2ipy==0.3
    - texsoup==0.2.0
    - traits==5.2.0
    - traitsui==6.1.3
    - twine==3.0.0
    - typogrify==2.0.7
    - ujson==1.35
    - w3lib==1.21.0
    - xlwt==1.3.0
    - yapf==0.28.0
