name: GeoPython37env
channels:
  - conda-forge
  - numba
  - rapidsai
  - mro
  - r
  - conda-forge/label/broken
#  - defaults
dependencies:
  - python==3.7
  - pip
  - numpy
  - pandas
  - docopt
  - gdal
  - pyproj
  - scikit-image
  - matplotlib-base
  - coverage
  - fiona
  - geopandas
  - pysal
  - affine
  - rasterstats >=0.12
  - bzip2
  - datashader
  - datashape
  - georasters
  - ipykernel
  - ipyparallel
  - openpyxl
  - pandas
  - pandas-datareader
  - pandana
  - pycountry
  - pysal
  - urbanaccess
  - r
  - rstudio
  - r-irkernel
  - statsmodels
  - sympy
  - rpy2
  - r-tidyr
  - r-tibble
  - r-dplyr
  - seaborn
  - scikit-learn
  - scipy
  - unidecode
  - urllib3
  - wikipedia
  - xlrd
  - jupyter_contrib_nbextensions
  - pip:
    - linearmodels
    - isounidecode
    - geonamescache
    - geocoder
    - git+https://github.com/dmsul/econtools
    - ecopy
    - geonamescache
    - googledrivedownloader
    - googletrans
    - ipystata
    - isodate
    - isounidecode
    - ldpred
    - linearmodels
    - pyreadstat
    - pytrends
    - simpledbf
    - simplejson
    - smartypants
    - stata-kernel
    - tabulate
